name: lamp

services:
  web:
    build: ./php-image
    container_name: php-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
  db:
    build: ./mariadb-image
    container_name: mariadb-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
    - my-db-volume:/var/lib/mysql
volumes:
  web:
    external: true
  my-db-volume:
